<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/sweetalert2.min.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/material.min.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/ripples.min.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/main.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/jspdf.min.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/html2canvas.esm.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/html2canvas.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/html2canvas.min.js"></script>
<script type="text/javascript" src="<?php echo SERVERURL; ?>vistas/js/script.js"></script>
